### ISSUE TITLE
2021-04-21 - NIST NVD data not parseable 

### ISSUE THREAD

**Issue by petedoyle** [stevespringett/CPE-Parser#76]
Hi Steve! I think this is an issue with the NIST NVD feed starting a few hours ago, but wanted to give you a heads up. Feels like an unintended format change at NIST, if you have any contacts.

Seeing Dependency-Check fail to parse this CPE (seems to parse via CPE-Parser):
```
cpe:2.3:a:cgiirc:cgi:irc:0.5.7:*:*:*:*:*:*:*
```

Seen in the 2011 data file from NIST:
```
➜  ~ curl --silent https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2011.json.gz | gunzip | grep -r -F "cpe:2.3:a:cgiirc:cgi:irc:0.5.7"
(standard input):          "cpe23Uri" : "cpe:2.3:a:cgiirc:cgi:irc:0.5.7:*:*:*:*:*:*:*",
```

Also see https://github.com/jeremylong/DependencyCheck/issues/3307.

```
org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to parse CPE: cpe:2.3:a:cgiirc:cgi:irc:0.5.7:*:*:*:*:*:*:*
org.owasp.dependencycheck.data.update.exception.UpdateException: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to parse CPE: cpe:2.3:a:cgiirc:cgi:irc:0.5.7:*:*:*:*:*:*:*
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:156)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:113)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.call(ProcessTask.java:40)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:749)
Caused by: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to parse CPE: cpe:2.3:a:cgiirc:cgi:irc:0.5.7:*:*:*:*:*:*:*
    at org.owasp.dependencycheck.data.nvdcve.CveDB.parseCpe(CveDB.java:1341)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.lambda$parseCpes$3(CveDB.java:1298)
    at java.util.ArrayList.forEach(ArrayList.java:1259)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.parseCpes(CveDB.java:1297)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.updateVulnerability(CveDB.java:880)
    at org.owasp.dependencycheck.data.update.nvd.NvdCveParser.parse(NvdCveParser.java:99)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.importJSON(ProcessTask.java:139)
    at org.owasp.dependencycheck.data.update.nvd.ProcessTask.processFiles(ProcessTask.java:152)
    ... 6 more
Caused by: us.springett.parsers.cpe.exceptions.CpeParsingException: Invalid CPE (too many components): cpe:2.3:a:cgiirc:cgi:irc:0.5.7:*:*:*:*:*:*:*
    at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:225)
    at us.springett.parsers.cpe.CpeParser.parse(CpeParser.java:77)
    at org.owasp.dependencycheck.data.nvdcve.CveDB.parseCpe(CveDB.java:1331)
    ... 13 more
```

**Comment by rpaasche** [comment]
Same for `cpe:2.3:a:xt-commerce:xt:commerce:3.0.4:*:*:*:*:*:*:*`

**Comment by petedoyle** [comment]
Closing. This was 100% bad data served by NIST (invalid CPEs) and is now resolved (see https://github.com/jeremylong/DependencyCheck/pull/3311). This library did wonderfully by explicitly rejecting bad data, with a good error message. Thank you!
